# Generated by Django 5.0 on 2024-02-22 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectclv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cobros',
            fields=[
                ('ID_COBROS', models.CharField(primary_key=True, serialize=False)),
                ('CODIGO_INTEGRANTE', models.CharField(null=True)),
                ('NUMERO_DE_RECIBO', models.CharField()),
                ('APELLIDO_PATERNO', models.TextField(null=True)),
                ('APELLIDO_MATERNO', models.TextField(null=True)),
                ('NOMBRES', models.TextField(null=True)),
                ('CODIGO_DE_GRUPO_INTEGRANTES', models.CharField(null=True)),
                ('FECHA_EMICION_RECIBO', models.DateTimeField()),
                ('FECHA_VENCIMIENTO_RECIBO', models.DateField()),
                ('MONEDA_A_PAGAR', models.CharField(null=True)),
                ('CODIGO_REFERENCIA_CLIENTE', models.CharField(null=True)),
                ('DESCRIPCION_COBRO_REALIZAR', models.TextField(null=True)),
                ('OBSERVACIONES_RECIBO', models.TextField(null=True)),
                ('INDICADOR_COBRO_MORA', models.CharField(null=True)),
                ('CODIGO_CONCEPTO_1', models.CharField(null=True)),
                ('IMPORTE_COBRO_COMPLETO', models.CharField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataConsolidado',
            fields=[
                ('ID_DATOS', models.CharField(db_column='IDDATOS', primary_key=True, serialize=False)),
                ('ITEM', models.IntegerField()),
                ('CODIGO_DE_PAGO', models.CharField(db_column='CODIGO DE PAGO', null=True, unique=True)),
                ('MZLTS', models.CharField(null=True)),
                ('CAPTACION', models.DateField(null=True)),
                ('ASESOR', models.TextField(null=True)),
                ('APELLIDO_PATERNO', models.TextField(db_column='APELLIDO PATERNO', null=True)),
                ('APELLIDO_MATERNO', models.TextField(db_column='APELLIDO MATERNO', null=True)),
                ('NOMBRES', models.TextField(null=True)),
                ('DOC', models.CharField(null=True)),
                ('NUMERO', models.CharField(db_column='NÚMERO', null=True)),
                ('DIRECCION', models.CharField(db_column='DIRECCIÓN', null=True)),
                ('DISTRITO', models.TextField(null=True)),
                ('PROVINCIA', models.TextField(null=True)),
                ('DEPARTAMENTO', models.TextField(null=True)),
                ('CELULAR', models.CharField(null=True)),
                ('EMAIL', models.CharField(null=True)),
                ('M2', models.CharField(null=True)),
                ('UBICACION', models.TextField(db_column='UBICACIÓN', null=True)),
                ('PRECIOVENTA', models.CharField(null=True)),
                ('INICIAL', models.CharField(null=True)),
                ('SALDO', models.CharField(null=True)),
                ('CUOTAS', models.IntegerField(null=True)),
                ('CUOTA', models.CharField(null=True)),
                ('INICIOPAGO', models.DateField(null=True)),
                ('CVENCIDAS', models.IntegerField(null=True)),
                ('CPAGADAS', models.IntegerField(null=True)),
                ('SVENCIDOS', models.CharField(null=True)),
                ('SPAGADOS', models.CharField(null=True)),
                ('COMENTARIO', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recaudaciones',
            fields=[
                ('ID_RECAUDACIONES', models.CharField(primary_key=True, serialize=False)),
                ('CODIGO_INTEGRANTE', models.CharField(null=True)),
                ('NUMERO_DE_RECIBO', models.CharField(null=True)),
                ('APELLIDOS_NOMBRES', models.TextField(null=True)),
                ('GRUPO', models.CharField(null=True)),
                ('DESCRIPCION_RECIBO', models.CharField(null=True)),
                ('IMP_RECIBO', models.CharField(null=True)),
                ('FECHA_VENCIMIENTO', models.DateField(null=True)),
                ('DIA_MORA', models.IntegerField(null=True)),
                ('IMP_MORA', models.CharField(null=True)),
                ('IMP_TOTAL', models.CharField(null=True)),
                ('FECHA_PAGO', models.DateField(null=True)),
                ('MZLTE', models.CharField(null=True)),
                ('FORMA_PAGO', models.TextField(null=True)),
                ('CALC_MORA', models.CharField(null=True)),
                ('FECHA_ACTUALIZADA', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resumen',
            fields=[
                ('ID_RESUMEN', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ID_INTEGRANTE', models.CharField()),
                ('FECHA_RESUMEN', models.DateField()),
                ('CVENCIDAS', models.IntegerField()),
                ('CPAGADAS', models.IntegerField()),
                ('SVENCIDOS', models.CharField()),
                ('SPAGADOS', models.CharField()),
            ],
        ),
    ]
